RecycleWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecycleWeb.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RecycleWeb/Controllers/RecyclableItemController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecycleWeb.Controllers
{
    
    public class RecyclableItemController : Controller
    {
        ApplicationDbContext _db = new ApplicationDbContext();


        public ActionResult List() {
            var ItemList = _db.RecyclableItems.ToList();

            return View(ItemList);
        }

        [HttpGet]
        public ActionResult Add() {
            var TypeList = _db.RecyclableTypes.ToList();
            ViewBag.TypesList = new SelectList(TypeList, "Id", "Type");
            return View();
        }

        [HttpPost]
        public ActionResult Add(RecyclableItem item) {

            var recyclableType = _db.RecyclableTypes.Find(item.RecyclableTypeId);


            if (item.Weight < recyclableType.MinKg || item.Weight > recyclableType.MaxKg) {
                ModelState.AddModelError("Weight", "Weight must be within the Minimum Kg ("+recyclableType.MinKg+ ") and Maxaximum Kg ("+recyclableType.MaxKg+") range.");
                var TypeList = _db.RecyclableTypes.ToList();
                ViewBag.TypesList = new SelectList(TypeList, "Id", "Type");
                return View(item);
            }

            if (ModelState.IsValid) {

                item.ComputedRate = recyclableType.Rate * item.Weight;


                _db.RecyclableItems.Add(item);
                _db.SaveChanges();

                return RedirectToAction("List"); 
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id) {
            var item = _db.RecyclableItems.Where(x => x.Id == id).FirstOrDefault();
            var TypeList = _db.RecyclableTypes.ToList();
            ViewBag.TypesList = new SelectList(TypeList, "Id", "Type");
            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(RecyclableItem item) {
            var data = _db.RecyclableItems.Where(x => x.Id == item.Id).FirstOrDefault();

            var recyclableType = _db.RecyclableTypes.Find(item.RecyclableTypeId);

            if (item.Weight < recyclableType.MinKg || item.Weight > recyclableType.MaxKg) {
                ModelState.AddModelError("Weight", "Weight must be within the Minimum Kg (" + recyclableType.MinKg + ") and Maxaximum Kg (" + recyclableType.MaxKg + ") range.");
                var TypeList = _db.RecyclableTypes.ToList();
                ViewBag.TypesList = new SelectList(TypeList, "Id", "Type");
                return View(item);
            }

            if (ModelState.IsValid && data != null) {

                item.ComputedRate = recyclableType.Rate * item.Weight;

                data.Weight = item.Weight;
                data.RecyclableTypeId = item.RecyclableTypeId;
                data.ItemDescription = item.ItemDescription;
                data.ComputedRate = item.ComputedRate;
                _db.SaveChanges();

                return RedirectToAction("List"); 
            }
            return View();
        }

        public ActionResult GetRateData(int id) {
            var type = _db.RecyclableTypes.FirstOrDefault(t => t.Id == id);
            if (type != null) {
                ViewBag.ratetype = type.Rate;
            }
            return View();
        }



        public ActionResult Delete(int id) {
            var data = _db.RecyclableItems.Where(x => x.Id == id).FirstOrDefault();
            _db.RecyclableItems.Remove(data);
            _db.SaveChanges();

            return RedirectToAction("List");
        }

        #region API CALLS

        [HttpGet]
        public ActionResult GetAll() {
            _db.Configuration.ProxyCreationEnabled = false;
            List<RecyclableItem> objItemList = _db.RecyclableItems.ToList();
            return Json(new { data = objItemList }, JsonRequestBehavior.AllowGet);
        }

        #endregion

    }
}

RecycleWeb/Controllers/RecyclableTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecycleWeb.Controllers
{
    public class RecyclableTypeController : Controller
    {
        // GET: Recycle
        ApplicationDbContext _db = new ApplicationDbContext();
        // GET: RecyclableType
        public ActionResult List() {
            var TypeList = _db.RecyclableTypes.ToList();
            return View(TypeList);
        }

        [HttpGet]
        public ActionResult Add() {
            return View();
        }

        [HttpPost]
        public ActionResult Add(RecyclableType item) {
            if (item.MinKg >= item.MaxKg) {
                ModelState.AddModelError("MaxKg", "Max weight must be greater than Min weight.");
                return View(item);
            }

            _db.RecyclableTypes.Add(item);
            _db.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(int id) {
            var item = _db.RecyclableTypes.Where(x => x.Id == id).FirstOrDefault();
            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(RecyclableType item) {
            if (item.MinKg >= item.MaxKg) {
                ModelState.AddModelError("MaxKg", "Max weight must be greater than Min weight.");
                return View(item);
            }

            var data = _db.RecyclableTypes.Where(x => x.Id == item.Id).FirstOrDefault();
            if (data != null) {
                data.Type = item.Type;
                data.Rate = item.Rate;
                data.MinKg = item.MinKg;
                data.MaxKg = item.MaxKg;
                _db.SaveChanges();
            }
            return RedirectToAction("List");
        }



        public ActionResult Delete(int id) {
            var recyclableType = _db.RecyclableTypes.Find(id);

            if (recyclableType == null) {
                return HttpNotFound();
            }
            var associatedItems = _db.RecyclableItems.Where(item => item.RecyclableTypeId == id);

            _db.RecyclableItems.RemoveRange(associatedItems);

            _db.RecyclableTypes.Remove(recyclableType);

            _db.SaveChanges();

            return RedirectToAction("List");
        }
    }
}

RecycleWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">RecyclableApp</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-6" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Recyclable Item</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>

        <section class="col-md-6" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Recyclable Type</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

RecycleWeb/Views/RecyclableItem/Add.cshtml
@model RecycleWeb.RecyclableItem

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="container-fluid">
        <!-- Use container-fluid for full-width layout -->
        <div class="card shadow border-primary mt-4">
            <div class="card-body p-4">
                <h4 class="text-center">Add Recyclable Item</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control shadow" } })
                        @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.ItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control shadow" } })
                        @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.RecyclableTypeId, "Recyclable Type", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.RecyclableTypeId, ViewBag.TypesList as SelectList, "Select Type", htmlAttributes: new { @class = "form-control shadow", id = "recyclableTypeDropdown" })
                        @Html.ValidationMessageFor(model => model.RecyclableTypeId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control shadow", id = "weight" } })
                        @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                    </div>
                </div>

                <input type="hidden" id="rate" value="@ViewBag.ratetype" />

                <div class="form-group row">
                    @Html.LabelFor(model => model.ComputedRate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ComputedRate, new { disabled = true, @readonly = "readonly", htmlAttributes = new { @class = "form-control shadow", id = "computedRate" } })
                        @Html.ValidationMessageFor(model => model.ComputedRate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <br />
                    <div class="col-md-offset-2 col-3">
                        <input type="submit" value="Create" class="btn btn-primary form-control border" />
                    </div>
                    <br />
                    <div class="col-md-offset-2 col-3">
                        <input type="reset" value="Reset" class="btn btn-primary form-control border" />
                    </div>
                    <br />
                    <div class="col-md-offset-2 col-3">
                        @Html.ActionLink("Back to List", "List", null, new { @class = "btn btn-secondary form-control border" })
                    </div>

                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            function updateSelectedValue() {
                var selectedValue = $('#recyclableTypeDropdown').val();
                console.log("Selected value: " + selectedValue);

                parseFloat($('#rate').val(selectedValue));
            }

            updateSelectedValue();

            $('#recyclableTypeDropdown').change(function () {
                updateSelectedValue();
            });

            $('#computedRate').prop('readonly', true);
            $('#rate, #weight').on('input', function () {
                var rate = parseFloat($('#rate').val()) || 0;
                var weight = parseFloat($('#weight').val()) || 0;
                var computedRate = rate * weight;

                $('#computedRate').val(computedRate.toFixed(2));
            });
        });
    </script>
}

RecycleWeb/Views/RecyclableItem/Delete.cshtml
@model RecycleWeb.RecyclableItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RecyclableItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ComputedRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComputedRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecyclableType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecyclableType.Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

RecycleWeb/Views/RecyclableItem/Edit.cshtml
@model RecycleWeb.RecyclableItem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>RecyclableItem</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.RecyclableTypeId, "RecyclableTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.RecyclableTypeId, ViewBag.TypesList as SelectList, "Select Type", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RecyclableTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ComputedRate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ComputedRate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ComputedRate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row">
        <br />
        <div class="col-md-offset-2 col-3">
            <input type="submit" value="Create" class="btn btn-primary form-control border" />
        </div>
        <br />
        <div class="col-md-offset-2 col-3">
            <input type="reset" value="Reset" class="btn btn-primary form-control border" />
        </div>
        <br />
        <div class="col-md-offset-2 col-3">
            @Html.ActionLink("Back to List", "List", null, new { @class = "btn btn-secondary form-control border" })
        </div>

    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RecycleWeb/Views/RecyclableItem/List.cshtml
@model IEnumerable<RecycleWeb.RecyclableItem>

@{
    ViewBag.Title = "List";
}

<h2 class="text-center">List</h2>

<div>
    @Html.ActionLink("Create New", "Add", null, new { @class = "btn btn-primary" })
</div>
<br />
<table class="table table-bordered">
    <thead>


        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ComputedRate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RecyclableType.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RecyclableType.Type)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ComputedRate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RecyclableType.Type)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>

</table>

RecycleWeb/Views/RecyclableType/Add.cshtml
@model RecycleWeb.RecyclableType

@{
    ViewBag.Title = "Add";
}


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="container-fluid">
        <!-- Use container-fluid for full-width layout -->
        <div class="card shadow border-primary mt-4">
            <div class="card-body p-4">
                <h4 class="text-center">Create Recyclable Type</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    <!-- Add row class for grid layout -->
                    @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control shadow" } })
                        @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control shadow" } })
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control shadow" } })
                        @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.MinKg, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MinKg, new { htmlAttributes = new { @class = "form-control shadow" } })
                        @Html.ValidationMessageFor(model => model.MinKg, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.MaxKg, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MaxKg, new { htmlAttributes = new { @class = "form-control shadow" } })
                        @Html.ValidationMessageFor(model => model.MaxKg, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <br />
                    <div class="col-md-offset-2 col-3">
                        <input type="submit" value="Create" class="btn btn-primary form-control border" />
                    </div>
                    <br />
                    <div class="col-md-offset-2 col-3">
                        <input type="reset" value="Reset" class="btn btn-primary form-control border" />
                    </div>
                    <br />
                    <div class="col-md-offset-2 col-3">
                        @Html.ActionLink("Back to List", "List", null, new { @class = "btn btn-secondary form-control border" })
                    </div>

                </div>

            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RecycleWeb/Views/RecyclableType/Delete.cshtml
@model RecycleWeb.RecyclableType

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RecyclableType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinKg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinKg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxKg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxKg)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

RecycleWeb/Views/RecyclableType/Edit.cshtml
@model RecycleWeb.RecyclableType

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>RecyclableType</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MinKg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MinKg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MinKg, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaxKg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxKg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxKg, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row">
        <br />
        <div class="col-md-offset-2 col-3">
            <input type="submit" value="Create" class="btn btn-primary form-control border" />
        </div>
        <br />
        <div class="col-md-offset-2 col-3">
            <input type="reset" value="Reset" class="btn btn-primary form-control border" />
        </div>
        <br />
        <div class="col-md-offset-2 col-3">
            @Html.ActionLink("Back to List", "List", null, new { @class = "btn btn-secondary form-control border" })
        </div>

    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RecycleWeb/Views/RecyclableType/List.cshtml
@model IEnumerable<RecycleWeb.RecyclableType>

@{
    ViewBag.Title = "List";
}

<h2 class="text-center">List</h2>

<div>
    @Html.ActionLink("Create New", "Add", null, new { @class = "btn btn-primary" })
</div>
<br/>
<table class="table  table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MinKg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxKg)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MinKg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxKg)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>

</table>

RecycleWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="//cdn.datatables.net/2.0.1/js/dataTables.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.1/css/dataTables.dataTables.min.css" />

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Recycle App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Recyclable-Item", "List", "RecyclableItem", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Recyclable-Type", "List", "RecyclableType", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="https://github.com/Dyastinn/Recycle">Github</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>